### ISSUE TITLE
Démarrage non désiré d'un subfleet suite à l'arrêt d'une instance Spot

### ISSUE THREAD

**Issue by nartya** [jcjorel/clonesquad-ec2-pet-autoscaler#15]
Bonjour Jean Charles,

Une stack clonesquad sur un de nos comptes a adopté un comportement imprévu jeudi 11/01 vers 2h.  Le démarrage soudain des instances de tout  un subfleet semble avoir été occasionné par l'interruption d'une instance Spot à 2h34. Suite à cet évènement Clonesquad doit normalement redémarrer une instance dans le même subfleet si nous nous fions aux messages de log ci-dessous mais nous avons remarqué une discordance avec le calcul fait pour déterminer le nombre d'ec2 à rallumer dans le code de Clonesquad.
 
<img width="564" alt="Capture d'écran 2024-01-11 164700" src="https://github.com/jcjorel/clonesquad-ec2-pet-autoscaler/assets/35570611/c366ae97-bc22-41a8-be1a-c6fa39e12182">

Nous avons envoyé un mail le jeudi 11 janvier avec en object "Démarrage non désiré d'un subfleet suite à l'arrêt d'une instance Spot" avec plus de détails sur notre soucis.

**Comment by jcjorel** [comment]
Thanks for reporting!
Fixed in v0.27.1
